source "https://rubygems.org"

gem "sinatra"
gem "mustache"
gem "ffi-rzmq"
gem "faye"
gem "thin"
gem "em"
gem "em-zeromq"
group :development, :test do
  gem "rspec"
  gem "cucumber"
  gem "capybara"
  gem "simplecov"
  gem "poltergeist"
  gem "pry"
end
