source "https://rubygems.org"

gem "sinatra"
gem "mustache"
gem "ffi-rzmq"
group :development, :test do
  gem "rspec"
  gem "cucumber"
  gem "capybara"
  gem "simplecov"
  gem "poltergeist"
  gem "pry"
end
